version: "3"
services:
  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - speedtest
  speedtester:
    build: "speedtest/."
    volumes:
      - speedtest-storage:/var/log/speedtest
    depends_on:
      - "influxdb"
    networks:
      - speedtest
  telegraf:
    build: "telegraf/."
    volumes:
      - speedtest-storage:/var/log/speedtest
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - "influxdb"
    networks:
      - speedtest
  grafana:
    build: "grafana/."
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - speedtest

networks:
  speedtest:

volumes:
  influxdb-storage:
  speedtest-storage:
  grafana-storage:
